language: php

php:
  - '7.4'

install:
  - composer install
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter

before_script:
  - ./cc-test-reporter before-build

script:
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml --whitelist src

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
